Models/ErrorViewModel.cs
namespace StarWars_Rating.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Components/CreateRatingViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StarWars_Rating.DataAccess.Models;

namespace StarWars_Rating.Components
{
    public class CreateRatingViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(int Id)
        {

            var rate = new Rate()
            {
                FilmId = Id
            };
            return await Task.FromResult((IViewComponentResult)View("CreateRatingViewComponent", rate));

        }
    }
}

Components/FilmsViewComponent.cs
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StarWars_Rating.API;

namespace StarWars_Rating.Components
{
    public class FilmsViewComponent : ViewComponent
    {
        private readonly ISwApiConnector _apiConnector;

        public FilmsViewComponent(ISwApiConnector apiConnector)
        {
            _apiConnector = apiConnector;
        }
        public async Task<IViewComponentResult> InvokeAsync(CancellationToken cancellationToken)
        {
            var model = await _apiConnector.GetFilmsAsync(cancellationToken);
            return await Task.FromResult((IViewComponentResult)View("FilmsViewComponent", model));
        }
    }
}

Components/RatingsViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StarWars_Rating.DataAccess;

namespace StarWars_Rating.Components
{
    public class RatingsViewComponent : ViewComponent
    {
        private readonly IRatingRepository _ratingRepository;

        public RatingsViewComponent(IRatingRepository ratingRepository)
        {
            _ratingRepository = ratingRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync(int Id)
        {
            var comments = await _ratingRepository.ListForFilmAsync(Id);
            return await Task.FromResult((IViewComponentResult)View("RatingsViewComponent", comments));
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using StarWars_Rating.Models;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using StarWars_Rating.API;
using StarWars_Rating.DataAccess;
using StarWars_Rating.DataAccess.Models;

namespace StarWars_Rating.Controllers
{
    public class HomeController : Controller
    {
        private readonly ISwApiConnector _swApiConnector;
        private readonly IRatingRepository _ratingRepository;


        public HomeController(ISwApiConnector swApiConnector, IRatingRepository ratingRepository)
        {
            _swApiConnector = swApiConnector;
            _ratingRepository = ratingRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> FilmDetails(int film, CancellationToken cancellationToken)
        {
            var loadedFilm = await _swApiConnector.GetFilmAsync(film, cancellationToken);
            return View(loadedFilm);
        }
        
        
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> AddComment(Rate rate)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("FilmDetails", new { film = rate.FilmId });
            }

            await _ratingRepository.CreateAsync(rate);
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/FilmDetails.cshtml
@model StarWars_Rating.API.Models.Film
@{
    ViewData["Title"] = "Film details";
}
<div class="text-center">
    <h1 class="display-4">@Model.Title</h1>
    <p>@Model.OpeningCrawl</p>
    @await Component.InvokeAsync("CreateRating", new { Model.Id })
    @await Component.InvokeAsync("Ratings", new { Model.Id })
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Star Wars</h1>
    @await Component.InvokeAsync("Films")
</div>

Views/Shared/Components/CreateRating/CreateRatingViewComponent.cshtml
@model StarWars_Rating.DataAccess.Models.Rate


@Html.HiddenFor(h => h.FilmId)
<form asp-controller="Home" asp-action="AddComment" asp-route-parent="@Model.FilmId" method="post">
    @Html.AntiForgeryToken()
    <input id="FilmId"
           name="FilmId"
           type="hidden"
           value="@Model.FilmId" />
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <input asp-for="@Model.UserName" name="UserName" placeholder="Add user name" />
        <span asp-validation-for="@Model.UserName"></span>
    </div>

    <div class="form-group">
        <select asp-for="@Model.Rating" asp-items="@Enumerable.Range(0, 11).Select(s => new SelectListItem(s.ToString(), s.ToString()))"></select>
    </div>
    <button type="submit" class="btn btn-primary">Add rate</button>
</form>

Views/Shared/Components/Films/FilmsViewComponent.cshtml
@model StarWars_Rating.API.Models.FilmCollection
<div class="col-md-12" style="padding-top:50px;">
    @foreach (var film in Model.Results)
    {
        <h1>@film.Title</h1>
        <h3>@film.Director</h3>
        @Html.ActionLink("Details", "FilmDetails", new { film = film.Id })
        <br />
    }
</div>

Views/Shared/Components/Ratings/RatingsViewComponent.cshtml
@model System.Collections.Generic.List<StarWars_Rating.DataAccess.Models.Rate>

@if (Model.Any()) { 
    <table>
        <thead>
        <td>User</td>
        <td>Rate</td>
        <td>Date</td>
        </thead>
        @foreach (var comment in Model)
        {
            <tr>
                <td>@comment.UserName</td>
                <td>@comment.Rating</td>
                <td>@comment.StoreDateTime.ToString()</td>
            </tr>
        }
    </table>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StarWars_Rating</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StarWars Films Rating</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - StarWars Films Rating
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>